#!/usr/bin/env bash

ROOTDIR="$( cd "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"

printhelp() {
   >&2 echo '
Usage: quetty-filter < -start STARTMODE >
A helper mode that starts quetty-fzf with the specified mode.
    '
}

startmode="word"

while (( "$#" ));do
  case $1 in
    -h|--help)
      printhelp
      exit 0
      ;;
    -start)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        startmode=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
   *)
     # quetty-fzf does not support any other arguments
     echo "Invalid Option: $1" 1>&2
     printhelp
     exit 1
     ;;
  esac
done

export QUETTYFZF_START="$startmode"
$ROOTDIR/tmux-butler
