#!/usr/bin/env bash
ROOTDIR="$( cd "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"
if [[ -f "$ROOTDIR/.env" ]]
then
        source "$ROOTDIR/.env"
fi

pastecontent="$BUTLERTMPDIR/tmux-butler-outputfile"
cat > $pastecontent
if [[ ! -s "$pastecontent" ]]
then
        exit 0
fi
cur_pane=$(tmux display-message -p "#D")

# Load contents to a tmux buffer named paste
tmux load-buffer -b paste $pastecontent
# Dump the contents from the paste buffer named paste
tmux paste-buffer -b paste -t $cur_pane
# Delete the paste buffer
tmux delete-buffer -b paste
